# Welcome to Jekyll!
#

# Site settings
title: sharegrowblog
description: |
  for inspiration, tips and true stories about job hunting
owner: Elleke Ketelaars
first_published: 2016
email: elleke.ketelaars@gmail.com
baseurl: ""
url: "http://www.sharegrow.eu"
social:
  github: https://github.com/eketelaars
  linkedin-square: https://linkedin.com/in/ellekeketelaars

# Build settings
markdown: kramdown

# Multi-language settings
# (https://github.com/Anthony-Gaudino/jekyll-multiple-languages-plugin)
languages: ["en", "fr"]

# Dependencies
gems:
  - jekyll-multiple-languages-plugin